# Generated by Django 4.0.5 on 2022-06-04 23:16

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0002_alter_especialidad_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha nacimiento'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='numero_celular',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Numero Celular'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='titulo_acreditacion_medica',
            field=models.FileField(upload_to='archivos/titulos', verbose_name='Titulo'),
        ),
    ]
