# Generated by Django 4.0.5 on 2022-06-05 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0003_alter_especialidad_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
    ]
