# Generated by Django 4.0.5 on 2022-06-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0004_medico_verificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='titulo_acreditacion_medica',
            field=models.FileField(upload_to='static/titulos', verbose_name='Titulo'),
        ),
    ]
