# Generated by Django 4.0.5 on 2022-06-26 21:48

from django.db import migrations, models
import django.db.models.deletion
import medicos.models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
        ('medicos', '0005_alter_medico_titulo_acreditacion_medica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('completado', models.BooleanField(default=False, verbose_name='Completado')),
                ('medico', models.ForeignKey(on_delete=medicos.models.Medico, to='medicos.medico')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
    ]
