# Generated by Django 4.0.5 on 2022-06-26 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0006_truno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truno',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.medico'),
        ),
    ]
