# Generated by Django 4.0.5 on 2022-06-26 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
        ('medicos', '0008_alter_truno_paciente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Truno',
            new_name='Turno',
        ),
    ]
