# Generated by Django 4.0.5 on 2022-07-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0009_rename_truno_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='direccion',
            field=models.CharField(default='', max_length=50, verbose_name='Direccion'),
        ),
    ]
